### ISSUE TITLE
can your editor delete housing items

### ISSUE THREAD

**Issue by Dejakester** [3nvy/wayfinder-save-editor#13]
I want to use helper coins and I can't. The game says my inventory is full. I suspect the 179 primal shrines and 40 deepwood fledglings I can't delete or sell in the game itself (not to mention orreries, other extra trophies, and pets). I downloaded your editor and it only looks like I can add housing items?

**Comment by 3nvy** [comment]
Adding an option to delete items should be fairly straightforward, Ill add it to the next version 👍 
That said, I think the new update allows to sell more housing items, so you could see if it allows you to sell those

**Comment by Dejakester** [comment]
Thank you
The issue is with the currently unsellable stuff I think... I don't need
184 primal shrines yet I have them and can't get rid of them. Hopefully
Airship fixes it.
Overall the game is somewhat glitchy
It was unplayable for team play last night - don't know why - vagaries of
Steam perhaps - my team hopes for better tonight

**Comment by 3nvy** [comment]
Yeah, I dont understand the decision behind some of these items not being soldable, especially considering they cound towards ur cap lol, but hey. Anyway, you should be able to bulk remove housing items with the latest editor version 👍
