### ISSUE TITLE
Suggestion: Feature Edit Different Point Values

### ISSUE THREAD

**Issue by Ikenowski** [3nvy/wayfinder-save-editor#14]
Feature to easily edit ability, affinity and talent points.

**Comment by 3nvy** [comment]
Do you mean adding additional points? or just move the assigned points around?

**Comment by Ikenowski** [comment]
Add additional points. Devs made it really easy to respec.

**Comment by 3nvy** [comment]
Right. Unfortunetaly, these points are not stored, they are calculated in runtime given other properties. For example, talent points are calculated via your wayfinder rank, lvl30 wayfinder rank means 30 talent points to your character. Then they are reduced based on the amount of talents actually placed in your save.

So while you can "manipulate" them by changing these values, you cant go higher that the pre-defined allocation. I do plan to have a character customization that allows you to change wayfinder level and stuff, but thats about as much it can be done via save editing

**Comment by Ikenowski** [comment]
Oh well, makes sense. Thanks for taking the time to respond. If editing levels and rank is the way to get there, that's just as good, maybe better.
