### ISSUE TITLE
Asking for update because of a new area, echos, new toon, housing stuff etc. 

### ISSUE THREAD

**Issue by Dejakester** [3nvy/wayfinder-save-editor#18]
Asking for you to update to include the new loot, echos, mats and stuff.  Thanking you in advance.

**Comment by Teysara** [comment]
love to see the update <3
greatjob so far

**Comment by beetalogist** [comment]
Yes. Don't know if this project is still ongoing, but hopefully it can get updated for the 1.0 release.

**Comment by 3nvy** [comment]
New version was just released: https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.5.0

It should contain the new DLC packs and items, tho I havent looked into new echos (are there actually new ones?) and may have missed some items.

Ill leave this issue opened for now so ppl can report missing items from 1.0

**Comment by inanmb** [comment]
Hi tank you for your work !

I think its missing "arc shard" new currency from the crucible vendor.

**Comment by Dejakester** [comment]
Thank you.  :)

**Comment by Dejakester** [comment]
First off. Thank you again. I enjoy playing the game and I purchased the Critical pretty pack with the  to support it.   I mostly use this resource to upgrade echoes I have already farmed.  

Several Echos from the Crucible and its dungeons are missing:  AS-621 VIGIL, Baleful Hollow, BC-XR-26 PROTOTYPE, Shadoweater, Starcrossed Lovers, Shield of Shadur, Wingblade Morne.  These are the ones I noticed so far. I have non epic versions of these. I haven't finished the new area yet as I am running it with a team and don't want to get ahead of them.  I have not fought three of the bosses (The Renegade, Teryssa the Silence, AS-713 CONFLUX) yet but they are all in the queue and prolly have echoes, crafting resources, and dedicated accessory drops. 

As someone else noticed the Dark Star Nights Maw from the Highlands and The Albatross from dungeons in the Deep are also missing. I didn't complain about these before I just farmed them myself.  I appreciate what you have done. 

In addition I notice that the new resource Tangled Spectra, and the new coin of the Crucible realm, Arc Shards, are also missing. I am not necessarily having difficulty obtaining these for myself, but others might be interested in the short cut. Also I didn't see the resource drops from the Crucible Bosses: Plague Bearer's Claw, Raven's Mask, Primal Core, and Severed Root. 

I have only just begun to get the new Accessories and the Engineer has 9 new Epic items to craft suggesting that there are at least 27 new Epic Accessories-the 4 I've acquired so far appear in the update as me having them. 

Once again thanks for the update.

**Comment by Teysara** [comment]
new stuff to take a look
about new npc shop from game version 1.0
problem is the first time i try to open that save game (with the editor 2.5.0) it'll read the weapon level as lv33 instead of 34 (the npc sell it at lv 34) while we just bought it at lv34 right?

it's just a minor problem because i can just edit the level back to 34 or higher like 35 36 37 38 later and it'll stay at that level without any problem later on

is there anything i should concern?


![1](https://github.com/user-attachments/assets/86a3b093-5df8-4af8-93bd-32de60c21bf4)

**Comment by Dejakester** [comment]
I thought I was pretty thorough about missing stuff, but I completely overlooked the housing items from the new area
So far I have gotten 
Bone Binder Banner
Blood Carver Banner
Talon Banner
Mushroom Tea Table
Box of Carrots
Meditation Crux
Shadurra Plant
Eldren Fabricator
Eldren Receptacle
Bone Binder Table
Shodden Bench
Mossen Rug
Mossen Side Table
Mossen Table
Mossen Lamp
Mossen Couch
Pebl (Pet)
Elvaas Plant
Dusty Mushroom Shelf
Kolcari Table
Vaas Plant
Shadhur Cable
Shadhur Conduit
Simple Planter
Mirosa Plant
Emberkiss Lamp
Syra'tol Plant
Gourd Pumpkin
Baby Pumpkin
Misshapen Pumpkin
Shadecrystal Lamp
Shadebloom Lamp
Nerus Plant
Hanging Royal Red
Topiary
I don't think any of these are in your update

**Comment by Dejakester** [comment]
> new stuff to take a look about new npc shop from game version 1.0 problem is the first time i try to open that save game (with the editor 2.5.0) it'll read the weapon level as lv33 instead of 34 (the npc sell it at lv 34) while we just bought it at lv34 right?
> 
> it's just a minor problem because i can just edit the level back to 34 or higher like 35 36 37 38 later and it'll stay at that level without any problem later on
> 
> is there anything i should concern?
> 
I dunno if it is much of a concern if you already are level 35 as you will be getting level 35 drops from the Crucible and its dungeons.  I don't think I would use my Arc Shards on those items from Warden Hass.  Just a thought.

**Comment by 3nvy** [comment]
> new stuff to take a look about new npc shop from game version 1.0 problem is the first time i try to open that save game (with the editor 2.5.0) it'll read the weapon level as lv33 instead of 34 (the npc sell it at lv 34) while we just bought it at lv34 right?
> 
> it's just a minor problem because i can just edit the level back to 34 or higher like 35 36 37 38 later and it'll stay at that level without any problem later on
> 
> is there anything i should concern?

Could be an XP mismatch on the curve table for weapon levels, I'll have a look

**Comment by 3nvy** [comment]
@Teysara Trying to look into the new vendor, can you point me to where it is located? (havent played much of the new update yet). Does it need to be unlocked? If so, do you mind sharing a save with it unlocked? Thanks :)

**Comment by Dejakester** [comment]
> @Teysara Trying to look into the new vendor, can you point me to where it is located? (havent played much of the new update yet). Does it need to be unlocked? If so, do you mind sharing a save with it unlocked? Thanks :)

The new vender is Warden Hass in the Crucible... but you will pick up weapons in game by just playing at a higher level... I don't know if the new weapons drop in Aurelian and Frostmarch & their dungeons though.  If you have run through the entire story to-date you should be able to just walk into the Crucible-at least it worked for me.

**Comment by 3nvy** [comment]
Ah great, found it. Thanks 👍 Will investigate the weapon level issue

**Comment by 3nvy** [comment]
K, found the issue. There was literally a 0.0125 exp deviation from my exp table and the games lol. Fix should come in the next version

**Comment by 3nvy** [comment]
All new items/weapons/echos/currencies should now be available on the latest release This is now available on the latest release https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.6.0

the fix for the weapon level upon buying from the vendor should also be fixed
