### ISSUE TITLE
Break saves

### ISSUE THREAD

**Issue by NitoSD** [3nvy/wayfinder-save-editor#20]
Saves load error after editing (and no saves viev in main menu). Different save file size after editing. Only one change: add Founder Coins from 0 to 7. Please some help.
[saves.zip](https://github.com/user-attachments/files/17531120/saves.zip)

**Comment by Teysara** [comment]
maybe a bug for you only bro
i have tried edit... 5 things
money , memory , echo level , potions amount
and founder coins (from zero to seven) like you ask
no problem no broken

**Comment by 3nvy** [comment]
It seems to actually be an issue with the re-compression of the savefile, which is weird because the save editor can recognize the save after its been compressed, pointing to teh fact that its been compressed correctly, but the game is rejecting the file 🤔 

Im having a better look into it

**Comment by 3nvy** [comment]
So, Im really at a bit of a loss on this one. Its true that if I edit the file you sent straight away it breaks it, and I cant really figure out why, everything looks ok but the game fails to uncompress the save and fails.

That said, what I did was load your save and change location to force a new save file, I did this by going to the Highlands. After this, I tried to edit the save again and it just worked 😕 

Im not exactly sure what could be causing this tbh, doesnt make much sense 🤔 I would suggest a couple things:

- Can you actually do what I did above? Load the game, go to the highlands, exit the game and try to edit the game then and see if it works

- Do you have steam cloud saves turned on? If so, can you turn them off and try the above again?

- If this still fails, can you try to verify the games Integrity and try again?

Whatever its causing this, it doesnt seem to be inreversible, but it seems to not accept the compressed file after wards for some reason 🤔

**Comment by NitoSD** [comment]
I load the game, go to the highlands, exit the game and edit save and then works :D Maybe not worked if saved in Skylight?
The other two points (verify and no cloud) are ok.

**Comment by Krigron** [comment]
Hi, i have the same problem. I go to the highlands and then edit saves and saves break. I too need 7 founder coins :D
[76561198054077500.zip](https://github.com/user-attachments/files/17546745/76561198054077500.zip)

**Comment by 3nvy** [comment]
@NitoSD It should definitely work in skylight, cause thats where I make all my edits 😂 But for some reason, some saves have some weird compression at some points that cause this 🤔 If you then return to skylight after successfully editing the save while in the Highlands, does it break again?

@Krigron Ill have a loko at ur saves 👍

**Comment by Qingyussx** [comment]
hi I also encountered the same problem, no matter which area I edited my save file, it would break😂The strangest thing is that when I open my file and I don't edit anything, I just click the Save key in the editor, my save file will show break

**Comment by lihengyang528** [comment]
I'm having the same issue. I tried to modify something with your save editor and then copy it to [another save editor](https://github.com/DumzGW/-WayfinderSaveEditor-python-) to compress and output save, which solves the problem, so I think there might be some minor issues with the compression.

**Comment by 3nvy** [comment]
Thanks for the feedback. Currently looking into different compression rates 🕵️

**Comment by NitoSD** [comment]
I will check this and write later. The only thing I changed additionally is the language from another to English.

**Comment by lihengyang528** [comment]
Perhaps this problem is caused by game language? I will try switching game languages later to see if it can solve this problem. Or it could be that the character name contains non English characters.

**Comment by lihengyang528** [comment]
I switched the game language to English and used the save editor, everything worked properly, so this issue should be caused by inconsistent save due to the game language. You can indicate in the README that you need to switch the game language to English and save again before use.

**Comment by 3nvy** [comment]
@lihengyang528 @NitoSD  Thanks for the feedback, amazing that does seem to be the case. I though that language was handled on the game configs instead of the save so I didnt pay that too much attention, but there seems to be a property in the save that retains the language of the game `areaName`, and it seems when on languages with special characters, that screws up the encoding of the save, even tho it should default to utf-8 🤔 

I'll try to look into this later, but for now @Krigron @Qingyussx can you try this? Load the game, change tha language to English, exist and then try to edit the save.

I'll change the README to add this fix for now

thanks for the investigation work 👍

**Comment by Qingyussx** [comment]
@3nvy I just changed the language of the game to English and the problem was solved. Thank you

**Comment by Krigron** [comment]
@3nvy The problem was in the custom translator. I turned it off, moved to the highlands and everything worked.
Thx)
