### ISSUE TITLE
some echo still missing from the editor

### ISSUE THREAD

**Issue by Teysara** [3nvy/wayfinder-save-editor#22]
or.... the editor can't detect it
(i got these from in-game enemy but when i open the editor to edit it... it doesn't appear in the editor)
such as these two
new search function is SUPER cool btw
![1](https://github.com/user-attachments/assets/86496c70-a664-41bd-837c-0c97fd3d34ab)

**Comment by 3nvy** [comment]
I suppose these may be new echos from 1.0

The save is capable of reading all the items from your inventory, but in order to add them, they need to be manually mapped on the save editor side.

I only added the dlc pack and the new wayfinder armor/cosmectics, Ill have a look at the new echos 👍

**Comment by Teysara** [comment]
alright thank you 
not in a hurry at all
please take your time relax

**Comment by 3nvy** [comment]
This is now available on the latest release https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.6.0
