### ISSUE TITLE
Suggestion: Dyes

### ISSUE THREAD

**Issue by KazzDaFish** [3nvy/wayfinder-save-editor#23]
Love the editor! Was just curious if you could add a function to unlock dyes?

Sorry if i've totally missed the comment section, first time using github lol

**Comment by 3nvy** [comment]
Its ok, here is fine ahah. Ill add a note to add a tab for dyes 👍

**Comment by KazzDaFish** [comment]
Legend! Thank you

**Comment by 3nvy** [comment]
This is now available on the latest release https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.6.0
