### ISSUE TITLE
Adding multiples of the same echoe

### ISSUE THREAD

**Issue by mushibugyo** [3nvy/wayfinder-save-editor#27]
Heya
I've encountered an issue adding multiples of the same echoes. Specifically, after adding them and logging back into the game I cannot equip the newly added echoes as it says "already equipped" (please note that I already have one equipped). Is this normal behaviour or am I doing something wrong? Any help would be greatly appreciated.
Cheers.

**Comment by 3nvy** [comment]
Weird, all added echos should have a distinct ID, so they should all be independent items. Let me have a look

**Comment by mushibugyo** [comment]
Heya 3nvy,

Did some more testing and I am positive that for some odd reason, when adding in multiples of the same echo, that only one is equip-able. Let me know if you need screen caps.

Cheers

**Comment by 3nvy** [comment]
So, had a bit of a look, I think this may actually be a limitation on the game 🤔 It happens with all echos, not just the ones added from the save. Once you add an echo, you cant equip the "same" echo on ur build, even if its a separate echo item.

Im pretty sure this wasnt the case before, maybe something they recently introduced 🤔

**Comment by Teysara** [comment]
you can equipped only 1 echo of the same name
>>it's normal game mechanic<<

**Comment by mushibugyo** [comment]
> So, had a bit of a look, I think this may actually be a limitation on the game 🤔 It happens with all echos, not just the ones added from the save. Once you add an echo, you cant equip the "same" echo on ur build, even if its a separate echo item.
> 
> Im pretty sure this wasnt the case before, maybe something they recently introduced 🤔

Wow, I am both shocked and appalled at my own ignorance. :( I never noticed that only one echo (of a specific type) could be equipped. Sad days indeed. Thanks a ton for checking and answering, I'll be more diligent before posting such questions in the future.
Cheers

**Comment by 3nvy** [comment]
Ahah its ok, I actually wasn't aware of this either, so just learned something aswell xD

This should actually be possible to change with modding, I was actually looking into it but didnt made much progress as of now
