### ISSUE TITLE
requesting new accessories

### ISSUE THREAD

**Issue by Teysara** [3nvy/wayfinder-save-editor#28]
![8](https://github.com/user-attachments/assets/6c441d23-6371-4e39-9339-7e7952843f80)
these new accessories are not in the editor yet
i just want to add the last piece of these accessory to complete the collection :)
hope you have time to take a look

(they're level 40 accessory that drop from new bosses in 1.0 mystic hunt)

**Comment by 3nvy** [comment]
These have been added and will be available in the next release. Thanks for raising 👍

**Comment by 3nvy** [comment]
These have been added in the new version :)

https://github.com/3nvy/wayfinder-save-editor/releases/tag/2.7.0
