### ISSUE TITLE
Kyros Fix Too Aggressive

### ISSUE THREAD

**Issue by Diorik** [3nvy/wayfinder-save-editor#7]
Using the Kyros fix to handle my busted Founder unlock, now he has maxed Affinity and Abilities, which would be cool, except he's still accumulating new points along and I can't spend those to clear the notification. 

Could the fix be adjusted to leave him in a more vanilla state? Even resetting to level 1 with a blank slate would be okay, we can burn Resonance cubes.

**Comment by 3nvy** [comment]
heya, thanks for reporting. You mean you got a kyros with maxed afinity and skills when u applied the fix? 🤔

**Comment by Diorik** [comment]
Yea. Before he was broke and couldn't add points like is mentioned on the fix button, and afterwards he was 100% maxed out, 25 in all affinities, all skills (which I hadn't unlocked yet), and full ability points. I made no edits to the raw structure or anything else that should have caused this AFAIK

**Comment by 3nvy** [comment]
So, Ive been unable to reproduce this. For me Kyros just stays at base level with no ability points assigned. Would yo umind sharing the savefile where this is happening? Would be interested in exploring whats causing this 🤔

**Comment by Diorik** [comment]
[WayfinderSave_9.zip](https://github.com/user-attachments/files/15891072/WayfinderSave_9.zip)
Attached is my latest, I don't have a file from before hitting the fix button, but I hope it can provide some clues.

**Comment by Diorik** [comment]
For some added context, I HAD played Kyros some while he was broke from the initial unlock, and I specifically had unlocked him before the game actually gave the ability to summon other Wayfinders. He was slightly more broke at the time (like not even having a stamina bar), but once I earned Summoning some of that fixed itself.

**Comment by 3nvy** [comment]
So, I can see whats wrong, I just dont know how this could have possibly have happened 😅
The item structure of the abilities and perks are all wrong, but the fix would add a base structure with none of the stuff you have on your save, so this is really puzzling me lol, maybe it picked up some weird, pre-existing structure when it applied the fix, but would be hard to tell w/t looking at the save before.

I can fix your save if you like :)

**Comment by 3nvy** [comment]
[WayfinderSave_9_kyros_fixed.zip](https://github.com/user-attachments/files/15891611/WayfinderSave_9_kyros_fixed.zip)

Let me know if it works :)

**Comment by Diorik** [comment]
Works great, thanks for that!
