### ISSUE TITLE
Mythic Awakening Essence

### ISSUE THREAD

**Issue by Tasiobg** [3nvy/wayfinder-save-editor#8]
Hi,
You can add **999** Mythic Awakening Essences by adding/updating this
```
{
  "name": "Part_GenericMythical_Essence",
  "equippedSlotId": "00000000000000000000000000000000",
  "equippedSlotName": "None",
  "count": 999,
  "itemFlags": 0
},
```

Inside this
```
"playerData": {
  "m_Version": 1,
  "m_InventoryData": {
    "m_Version": 9,
    "m_FungibleItems": [
```

**Comment by 3nvy** [comment]
Heya 👋  Mythical essence will fall under the "Weapon Crafting" tab that Im planing after Im done with accessories, so it will be there alongside all the parts required for each weapon. But thanks for sharing 🙌
